#!/bin/bash

SNIFF_HOST=$1
SNIFF_INTERFACE=$2

if [ -z "$SNIFF_HOST" ]; then
  echo "Usage:  sniffles [interface|eth0|wlan0|etc...] [host]"
  exit 1
fi

if [ -z "$SNIFF_INTERFACE" ]; then
  if [[ `uname` == "Darwin" ]]; then
    SNIFF_INTERFACE=`route get $SNIFF_HOST | grep 'interface' | awk -F':' '{print $2}' | tr -d '[[:space:]]'`
  elif [[ `uname` == "Linux" ]]; then
    SNIFF_INTERFACE=`ip route get "$(dig $SNIFF_HOST +short)" | head -n 1 | awk '{print $5}'`
  else
    echo "Cannot auto-determine network interface."
    echo "Please provide it as an arguement and try again."
    exit 1
  fi
fi

sudo tcpdump -v -X -s 1500 -i $SNIFF_INTERFACE host $SNIFF_HOST
